global:
  scrape_interval: 5s
  evaluation_interval: 5s
  external_labels:
    cluster: demo
    namespace: demo

scrape_configs:
  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
      - targets:
        - 192.168.137.1:8081
  - job_name: prometheus
    scrape_interval: 5s
    static_configs:
      - targets:
        - 192.168.137.1:9090
  - job_name: node
    static_configs:
      - targets:
        - 192.168.137.1:9100  
  - job_name: mimir
    static_configs:
      - targets:
        - 192.168.137.1:9009

remote_write:
  - url: http://192.168.137.1:9009/api/v1/push
    # Add X-Scope-OrgID header so that Mimir knows what tenant the remote write data should be stored in.
    # In this case, our tenant is "demo"
    headers:
      X-Scope-OrgID: demo

    